on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config check libsubunit-dev cppcheck doxygen valgrind
    - name: cppcheck
      run: cppcheck --force --enable=warning --error-exitcode=1 .
    - name: build
      run: |
        # prepare build folders
        mkdir build
        # build crypto, run tests, build package
        cd build
        cmake -DBUILD_CRYPTO_TESTING=on -DBUILD_CRYPTO_DOCUMENTATION=on ..
        make test package doc
        sudo make install
        cd ..
        make
        make clean check
